removed m.room.message.feedback
matrix-org/matrix-spec pull request #1035
Opened 2022-04-26 14:40 UTC by thomaslantern

Signed-off-by: Thomas Scott <shikisha@hotmail.com>

2022-05-02 01:15 UTC, turt2live requested changes
Thanks! This just needs a changelog entry for "Removed `m.room.message.feedback` per MSC0000." (whatever that MSC is).

2022-05-02 15:30 UTC, thomaslantern commented
> Thanks! This just needs a changelog entry for "Removed `m.room.message.feedback` per [MSC0000](https://github.com/matrix-org/matrix-spec-proposals/issues/0000)." (whatever that MSC is).

Changelog entry added, thanks!

2022-05-05 21:23 UTC, turt2live commented on changelogs/client_server/newsfragments/3582.clarification
> +Removed m.room.message.feedback per MSC3582.
```suggestion
Removed `m.room.message.feedback` per [MSC3582](https://github.com/matrix-org/matrix-spec-proposals/pull/3582).
```

2022-05-05 21:23 UTC, turt2live approved these changes
Thanks!

2022-05-05 21:34 UTC, merged