Clarify that /invite will respond with 200 if the user is already in the room
matrix-org/matrix-spec pull request #1084
Opened 2022-05-25 08:54 UTC by Half-Shot

Potentially fixes #1083 

I *believe* this might fall within the scope of minor text clarification rather than requiring a full MSC, as it's a behavior that has been in action for a long time (for Synapse at least, and possibly other implementations?). This doesn't seek to correct the response.

2022-05-25 20:24 UTC, turt2live requested changes
This needs a changelog entry, and evidence that this is in fact the case please :)

2022-06-30 21:59 UTC, turt2live commented
@Half-Shot are you able to take a look at this?

2022-06-30 22:18 UTC, Half-Shot commented
Yep, let me sort that out.

2022-07-04 19:17 UTC, turt2live approved these changes
otherwise lgtm

2022-07-04 19:17 UTC, turt2live commented on changelogs/client_server/newsfragments/1084.clarification
> +Mention that the /rooms/$roomId/invite endpoint will return a 200 response if the user is already invited to the room.
```suggestion
Mention that the `/rooms/{roomId}/invite` endpoint will return a 200 response if the user is already invited to the room.
```

2022-07-04 19:19 UTC, merged