Quick hacky version dropdown
matrix-org/matrix-spec pull request #1131
Opened 2022-06-16 01:01 UTC by DMRobertson

Very rough prototype. Corners cut everywhere. Bad javascript habits. I learned babby's first web development back when the <font> tag was cool.

Closes #951. (Sort of. We'd need to regenerate /v1.1 and /v1.2 to include the switcher.

2022-06-16 01:01 UTC, DMRobertson commented
I emulated the `spec.matrix.org` deployment as follows:

```
git branch -D dmr/v1.2
git checkout -b dmr/v1.2 v1.2
git cherry-pick dmr/version-switcher
# resolve merge and complete the cherry-pick

git branch -D dmr/v1.1
git checkout -b dmr/v1.1 v1.1
git cherry-pick dmr/version-switcher
# resolve merge and complete the cherry-pick

git switch dmr/version-switcher
hugo --baseURL /unstable -d spec/unstable
git switch dmr/v1.2
hugo --baseURL /v1.2 -d spec/v1.2
hugo --baseURL /latest -d spec/latest
git switch dmr/v1.1
hugo --baseURL /v1.1 -d spec/v1.1

python -m http.server --directory spec
```

2022-06-16 01:04 UTC, DMRobertson commented
Will leave this parked for now, but can come back to it if there's interest.

2022-06-16 10:19 UTC, DMRobertson commented
> I'm interested. Can you give it a newsfragment so that the CI runs and we can see what it looks like?

Part of the trouble is that Netlify only builds one version of the spec, rather than all the versions (`/v1.1/, /v1.2/, /latest/, /unstable/`) hosted on spec.matrix.org

2022-06-16 10:51 UTC, DMRobertson commented
Here's a demo I recorded locally. Unfortunately OBS studio wasn't capturing the dropdown menu that pops up, but it's hopefully convincing enough.

https://user-images.githubusercontent.com/8614563/174054878-0acd7cab-be32-4bc2-86d4-353b0f639727.mp4

2022-06-30 22:01 UTC, turt2live commented
that video looks good enough imo, and the code is good enough too. What are the concerns keeping this in draft?

2022-06-30 22:03 UTC, DMRobertson commented
> What are the concerns keeping this in draft?

Nothing as such, other than it being a big hack. It could use some hands-on testing from others too.

I'm not sure how the spec gets deployed. This would need a new version of v1.1 and v1.2 (and now v1.3) to be built which includes the selector.

2022-06-30 22:07 UTC, turt2live commented
We can try to build v1.1, v1.2, and v1.3 again though if it ends up not working out then ohwell.jpg - we already don't have links for r0.5.0 (for example).

2022-07-12 14:35 UTC, richvdh commented
Correct me if I'm wrong, but does this mean that old spec versions will not include newer spec versions on the dropdown, unless we rebuild all previous spec versions on each release? That doesn't sound entirely tenable.

Can we populate the list of of versions from a separate `https://spec.matrix.org/versions.json` or something?

2022-07-14 10:28 UTC, richvdh requested changes
ok, I don't think rebuilding all past versions of the spec on each release is something we particularly want to do.

Can you make the javascript populate the dropdown from a json file at `/versions.json` or something?

2023-12-12 13:00 UTC, closed without merging