Issue #1231/Update spelling in s2s authorization
matrix-org/matrix-spec pull request #1431
Opened 2023-02-12 15:14 UTC by saiprakash2

2023-02-13 17:40 UTC, turt2live requested changes
Thanks for the contribution! I've already fixed the PR title and description, but please review https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst when you get a chance.

Primarily, this needs a changelog entry to cover the typo.

2023-02-15 19:42 UTC, saiprakash2 commented
I added the change log entry.

2023-02-15 21:07 UTC, turt2live commented on changelogs/server_server/newsfragments/1431.clarification
> +Update spelling in s2s authorization.
```suggestion
Fix various typos throughout the specification.
```

2023-02-15 21:07 UTC, turt2live approved these changes
Thanks!

2023-02-15 21:09 UTC, merged