Notify additionally access token required when "require_auth_for_profile_requests" is True for _matrix/client/v3/profile/
matrix-org/matrix-spec pull request #1445
Opened 2023-02-22 12:25 UTC by hari01584

Read [this synapse issue](https://github.com/matrix-org/synapse/issues/15118) for background information.

Initially the spec didn't account for the need of access token in case when _require_auth_for_profile_requests_ is true, In that case the API endpoint _GET /_matrix/client/v3/profile/ will return 401 Unauthorized, Updated spec to reflect on this.

2023-02-22 13:16 UTC, KitsuneRal approved these changes

2023-02-22 17:09 UTC, turt2live requested changes
Synapse references do not belong in the spec. At a technical level, Synapse's feature is non-compliant (and would require an MSC to be made compliant).

2023-04-25 09:44 UTC, richvdh commented
@hari01584 are you interested in continuing to work on this pull request?

2023-06-20 16:11 UTC, richvdh commented
Thanks for your contribution. I'm going to close this for now as the changes requested haven't been made. If you're interested in continuing to work on this please let us know and we can reopen the pull request. Thanks!

2023-06-20 16:11 UTC, closed without merging