Add spec for MSC2746
matrix-org/matrix-spec pull request #1511
Opened 2023-05-04 11:12 UTC by dbkr

Adds https://github.com/matrix-org/matrix-spec-proposals/pull/2746

2023-05-16 21:39 UTC, uhoreg requested changes

2023-05-16 21:39 UTC, uhoreg commented on data/event-schemas/schema/m.call.negotiate.yaml
> +  This MSC also proposes clarifying the `m.call.invite` and `m.call.answer`
Shouldn't refer to "This MSC" in the spec.  I think this paragraph needs to be applied to the `m.call.invite` and `m.call.answer` schemas.

2023-05-17 08:48 UTC, dbkr commented on content/client-server-api/modules/voip_events.md
> +any streamless tracks. Note that in the Javascript WebRTC API, this means
Well, we don't have to but since it is so tied to browsers, it feels nice to explicitly explain what that means to b as helpful as possible.

2023-05-17 08:59 UTC, dbkr commented on data/event-schemas/schema/m.call.hangup.yaml
> +   * `ice_failed` which means no media connection could be established). Note that, in the case of
Mm, yes, fairly sure this didn't come out as intended.

2023-05-17 13:29 UTC, dbkr commented on data/event-schemas/schema/m.call.hangup.yaml
> +      version:
Yeah, this is neater. The only downside is that it repeats all the fields from a room event and I'm not sure how to make it not do that.

2023-05-17 22:08 UTC, uhoreg approved these changes
lgtm modulo some suggestions

2023-05-17 22:08 UTC, uhoreg commented on data/event-schemas/schema/m.call.reject.yaml
> +  a call is always implicitly because the user chose not to answer it.
```suggestion
  a call is always implicitly because the user chose not to answer it.
x-addedInMatrixVersion: "1.7"
```

2023-05-17 22:08 UTC, uhoreg commented on data/event-schemas/schema/m.call.select_answer.yaml
> +    "description": "This event is sent by the caller's client once it has decided which other client to talk to, by selecting one of multiple possible incoming `m.call.answer` events. Its `selected_p
```suggestion
    "description": "This event is sent by the caller's client once it has decided which other client to talk to, by selecting one of multiple possible incoming `m.call.answer` events. Its `selected_party_id` field indicates the answer it's chosen. The `call_id` and `party_id` of the caller is also included. If the callee's client sees a `select_answer` for an answer with party ID other than the one it sent, it ends the call and informs the user the call was answered elsewhere. It does not send any events. Media can start flowing before this event is seen or even sent.  Clients that implement previous versions of this specification will ignore this event and behave as they did before.",
    "x-addedInMatrixVersion": "1.7"
```

2023-05-23 18:04 UTC, turt2live reviewed
To fix the build

2023-05-23 18:04 UTC, turt2live commented on data/event-schemas/schema/m.call.select_answer.yaml
> +    "x-addedInMatrixVersion": "1.7"
```suggestion
    "x-addedInMatrixVersion": "1.7",
```

2023-05-23 18:29 UTC, turt2live commented
Looks like all threads are resolved here - merging.

2023-05-23 18:29 UTC, merged