Added missing type enum for m.reaction
matrix-org/matrix-spec pull request #1552
Opened 2023-05-31 14:36 UTC by chebureki

The specification does not specify the `m.reaction` for the event type

2023-05-31 15:30 UTC, chebureki commented
> Thanks! Please could you include a newsfragment file, per https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#adding-to-the-changelog?
> 
> Please try to phrase it in terms of the change to the rendered spec.

just did :)

2023-06-01 10:14 UTC, richvdh requested changes

2023-06-01 10:14 UTC, richvdh commented on changelogs/client_server/newsfragments/1552.clarification
> +Added missing enumerated type for the m.reaction event.
Please could you try to phrase this in a way that a reader of the spec will understand?

2023-06-20 16:10 UTC, richvdh commented
@chebureki are you still interested in working on this?

2023-06-23 09:14 UTC, chebureki commented
> @chebureki are you still interested in working on this?

I apologize, got busy with life.
We could rephrase it as. If you have a better idea, feel free to change it :)
> Fixed missing type field for reaction event

2023-06-23 09:31 UTC, richvdh commented on changelogs/client_server/newsfragments/1552.clarification
> +Added missing enumerated type for the m.reaction event.
```suggestion
Fix missing `type` property for the m.reaction event.
```

2023-06-23 09:35 UTC, richvdh commented
Wait, does this actually change the content of the spec at all?

https://pr1552--matrix-spec-previews.netlify.app/client-server-api/#mreaction looks identical to https://spec.matrix.org/v1.7/client-server-api/#mreaction

2023-07-04 12:51 UTC, richvdh commented on changelogs/client_server/newsfragments/1552.clarification
> +Fix missing `type` property for the m.reaction event.
```suggestion
Fix missing `type` property in the JSON schema definition of the `m.reaction` event.  Contributed by @chebureki.
```

2023-07-04 12:51 UTC, richvdh approved these changes
Thanks; sorry it took me a while to grok what was going on here.

2023-07-04 12:52 UTC, merged