Improve feature profile summary table styling
matrix-org/matrix-spec pull request #1599
Opened 2023-07-13 10:39 UTC by not-my-profile

This PR improves the styling of the [feature profile summary table](https://spec.matrix.org/v1.7/client-server-api/#summary) in the Client-Server API specification:

| Before | After |
|----|---|
|![image](https://github.com/matrix-org/matrix-spec/assets/73739153/317ee309-1c91-4d47-8053-f7ec6960c2a9) |![image](https://github.com/matrix-org/matrix-spec/assets/73739153/e3b0522a-50ec-44b6-9672-7c583dad8257)

2023-07-19 08:31 UTC, richvdh requested changes
Thank you for the contribution.

It seems quite complicated, though. Could we achieve much the same effect rather more simply just by making the "Required" text **bold** ?

Please do make sure that your changes are well-commented to help future maintainers understand. I've made some suggestions.

2023-07-19 08:31 UTC, richvdh commented on assets/scss/custom.scss
> +    right: 0;
Some comments would be nice.

```suggestion
    // expand to fill the entire table cell
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
```

2023-07-19 08:31 UTC, richvdh commented on assets/scss/custom.scss
> +    z-index: -1;
why is this required?

2023-07-19 08:31 UTC, richvdh commented on assets/scss/custom.scss
> +    position: relative;
I think this is something to do with the `span` resizing? comment it, please

2023-07-19 08:31 UTC, richvdh commented on assets/scss/custom.scss
> +.summary-table {
I think this makes the `!important` on the `padding` unnecessary:

```suggestion
table.summary-table {
```

2023-07-19 08:31 UTC, richvdh commented on assets/scss/custom.scss
> +    padding: .3rem 0.75rem !important;
Comment, please:

```suggestion
    // use a more compact table layout than the default.
    padding: .3rem 0.75rem !important;
```

2023-07-19 08:31 UTC, richvdh commented on config.toml
> +      block = true  # used by the summary-table shortcode
it would be nice to give a quick example of what it actually does. And/or link to the documentation

2023-07-19 08:35 UTC, richvdh commented
Please also take a look at the [contributing guide](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst), particularly with respect to [changelog entries](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#adding-to-the-changelog) and [sign-off](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#sign-off).

2023-10-11 10:41 UTC, richvdh commented
@not-my-profile are you still interested in working on this?

2023-10-11 15:11 UTC, not-my-profile commented
Sorry that I haven't replied. Thanks for the review ... your feedback is very reasonable and appreciated. I unfortunately am currently busy with other projects. I might circle back to this at some point in the future but can't tell you when.

2023-10-12 10:50 UTC, richvdh commented
@not-my-profile understood, and no need to apologise.

If it's unlikely you'll be working on this in the near future, then rather than keeping this PR open indefinitely, I'll go ahead and close it for now. That's not to say we're not interested in the work, and if you get a chance to pick it up again, do give us a ping and we'll be happy to reopen it!

Thanks for the contribution in any case.

2023-10-12 10:50 UTC, closed without merging