Note that /logout doesn't take a body
matrix-org/matrix-spec pull request #1644
Opened 2023-09-22 16:48 UTC by reivilibre

`/logout` says it does not take a request body[^1], so add it to the list of exceptions at the top.

I note that Complement does not send a request body for this endpoint, so that must mean Synapse and Dendrite allow that.

[^1]: https://spec.matrix.org/v1.8/client-server-api/#post_matrixclientv3logout

2023-10-03 20:42 UTC, richvdh requested changes
Hrm, this makes me sad.

I *want* to claim that this is misleading wording on behalf of the `/logout` endpoint definition, and a misfeature in complement/synapse/dendrite, rather than an indication that the body should actually allowed to be empty.  Granting `/logout` an exception in this way very much puts it in a class of one.

On the other hand, it's clearly been this way since forever, and Element-Web relies upon it. So I guess I have to suck up the fact that there's an exception and make it something to fix for OIDC.

Anyway, `/logout/all` has the same problem I think.

2023-10-03 20:42 UTC, richvdh commented on changelogs/client_server/newsfragments/1644.clarification
> +Clarify specification by adding `/logout` to the overview list of endpoints that don't take a request body.
Note that the other two in the list *do* take a request body; it's just not a JSON object. Could you reword slightly?

2023-10-03 20:42 UTC, richvdh commented on content/client-server-api/_index.md
> +and [`POST /_matrix/client/v3/logout`](#post_matrixclientv3logout),
it might be worth emphasising what the exceptions do require.

2023-10-03 20:42 UTC, richvdh commented
(we should file a 'Wart' issue against the spec for this)

2024-02-27 13:55 UTC, richvdh commented
@reivilibre would you be able to update this?

2024-06-05 15:10 UTC, reivilibre commented
Issue created at https://github.com/matrix-org/matrix-spec/issues/1845 but I don't have the ability to add a Wart label

2024-06-06 10:19 UTC, richvdh commented on content/client-server-api/_index.md
> +  which does not take any request body.
logout/all has the same problem:

```suggestion
- [`POST /_matrix/client/v3/logout`](#post_matrixclientv3logout) and
  [`POST /_matrix/client/v3/logout/all`](#post_matrixclientv3logoutall),
  which take an empty request body.
```

2024-06-06 10:19 UTC, richvdh commented on content/client-server-api/_index.md
> +  which takes any type of request body depending on what type of media is to be uploaded.
I feel like this is getting a bit verbose. (And sorry, I know I previously encouraged you to spell this out more.)

Can we combine them into a single entry:

```suggestion
- [`POST /_matrix/media/v3/upload`](#post_matrixmediav3upload) and 
  [`PUT /_matrix/media/v3/upload/{serverName}/{mediaId}`](#put_matrixmediav3uploadservernamemediaid),
  both of which take the uploaded media as the request body.
```

2024-06-11 14:21 UTC, richvdh approved these changes
Thanks!

2024-06-11 14:22 UTC, merged