Add spec for shared-history room keys (MSC3061)
matrix-org/matrix-spec pull request #1655
Opened 2023-10-04 00:43 UTC by uhoreg

spec PR for https://github.com/matrix-org/matrix-spec-proposals/pull/3061

2023-10-04 07:51 UTC, poljar reviewed
Should we push this to the spec, considering the problems which were subsequently discovered with this MSC3061?

2023-10-10 17:22 UTC, richvdh requested changes
Pending a decision about wtf we are doing here

2024-02-27 18:08 UTC, richvdh commented
Apparently there are security concerns, specifically around sharing keys for past messages. We'll disclose more details in a few weeks, and then we can decide how best to proceed here.

2024-03-10 19:59 UTC, Johennes commented on content/client-server-api/modules/end_to_end_encryption.md
> +for old messages with them.  For example, clients can share keys for old
```suggestion
for old messages with them. For example, clients can share keys for old
```

2024-03-19 21:27 UTC, turt2live reviewed
clearing team review request while awaiting security impact

2024-07-08 06:37 UTC, murlock1000 commented
With the recent migration of element clients to the rust SDK this introduced a regression of the spec. Any updates on this @turt2live ?

2024-10-15 12:06 UTC, dkasak commented
The reason this was blocked was disclosed in https://matrix.org/blog/2024/10/security-disclosure-matrix-js-sdk-and-matrix-react-sdk/ and the associated advisories. The plan forward is outlined in [this section](https://matrix.org/blog/2024/10/security-disclosure-matrix-js-sdk-and-matrix-react-sdk/#proposed-specification-changes).

2024-10-16 17:41 UTC, turt2live requested changes
Formalizing "proposed spec changes" at https://matrix.org/blog/2024/10/security-disclosure-matrix-js-sdk-and-matrix-react-sdk/#proposed-specification-changes as requiring action. That future MSC will have impact on this spec PR's text.

2024-10-29 16:58 UTC, richvdh commented
MSC3061 has been un-merged, so we're going to abandon this for now.

2024-10-29 16:58 UTC, closed without merging