chore: Make clearer in the example that the fallback prefix sequence should be repeated for each line
matrix-org/matrix-spec pull request #1690
Opened 2023-12-04 09:44 UTC by Konubinix

I needed to read the spec twice to make sure it was the case.

Also, I encountered an implementation of matrix that added the sequence only for the first line.

I believe that making the first example of the chapter show several lines will make less likely such mistakes in the future.

2023-12-05 16:20 UTC, richvdh commented
I'm sorry you found it a chore

2023-12-05 16:22 UTC, richvdh requested changes
Thank you for your contribution. Please take a look at the [contributing guide](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst), particularly with respect to [changelog entries](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#adding-to-the-changelog) and [sign-off](https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#sign-off).

2023-12-06 10:28 UTC, Konubinix commented
Thank you for the answer,

I will read the document and adjust the PR accordingly.

-- 
Konubinix
GPG Key    : 7439106A
Fingerprint: 5993 BE7A DA65 E2D9 06CE  5C36 75D2 3CED 7439 106A

2023-12-09 18:21 UTC, Konubinix commented
IIUC, the only thing I needed to do in that particular case was to sign off my
commit, right?

So, I did it :-)

Please let me know if there is something I missed.

2023-12-09 18:23 UTC, Konubinix commented
I understand that updating the changelog is done only when the API changes.

2023-12-19 15:03 UTC, richvdh commented
Yeah the wording is unclear; apologies. (https://github.com/matrix-org/matrix-spec/pull/1697 should improve it.)

Please could you create `changelogs/client_server/newsfragments/1690.clarification` with a brief summary (`Clarify example for reply fallbacks.` or somesuch).

2024-01-15 12:33 UTC, richvdh commented on changelogs/client_server/newsfragments/1690.clarification
> +Make clearer in the example that the fallback prefix sequence should be repeated for each line.
```suggestion
Make clearer in the example for reply fallbacks that the prefix sequence should be repeated for each line.
```

2024-01-15 12:34 UTC, richvdh approved these changes
Thank you for the contribution! Sorry the review took a while.

2024-01-15 12:35 UTC, merged