Clarify that redaction events are subject to auth rules
matrix-org/matrix-spec pull request #1824
Opened 2024-05-18 14:09 UTC by Kladki

[Context](https://matrix.to/#/%23matrix-spec%3Amatrix.org/%24Y5gvmJK2fv-HwBRURrf6cHMtFvmqrTvfZ9Lur4fqDhE?via=ahouansou.cz&via=l1qu1d.net&via=0x1a8510f2.space&via=the-apothecary.club): there was a misunderstanding about how redactions interact with auth rules.

2024-05-28 15:39 UTC, richvdh commented
... though having read the diff I think I can guess what the misunderstanding was.

2024-05-28 15:41 UTC, Kladki commented
The misunderstanding was that 'are not explicitly part of the auth rules' and 'should always fall into "10. Otherwise, allow".' was interpreted as meaning that redaction events are not subject to the auth rules at all.

2024-05-28 16:07 UTC, richvdh requested changes
Thanks for this. I think it helps, but I think it could be clearer.

Also, please add a sign-off to the PR, per https://github.com/matrix-org/matrix-spec/blob/main/CONTRIBUTING.rst#sign-off

2024-05-28 16:07 UTC, richvdh commented on content/rooms/v6.md
> +later stage: see the [Redactions](#redactions) section below for more information.
I find this use of "they" and "them" to mean different things rather confusing. I think we can do better.

Also, you've changed the link, to refer to the wrong section.

```suggestion
`m.room.redaction` events are subject to auth rules in the same way as any other event.
In practice, that means they will normally be allowed by the auth rules, unless the
`m.room.power_levels` event sets a power level requirement for `m.room.redaction`
events via the `events` or `events_default` properties. In particular, the /redact
level/ is **not** considered by the auth rules.

The ability to send a redaction event does not mean that the redaction itself should
be performed. Receiving servers must perform additional checks, as described in
the [Handling Redactions](#handling-redactions) section below.
```

Suggest putting all this in a `{{% boxes/note %}}` box next to the other one, below.

2024-05-28 16:07 UTC, richvdh commented on content/rooms/v6.md
> +later stage: see the [Redactions](#redactions) section below for more information.
Likewise for the other room versions.

2024-05-28 16:38 UTC, richvdh commented on content/rooms/v6.md
> +later stage: see the [Redactions](#redactions) section below for more information.
yeah, I meant it to be italic. There are other references to "redact level" in the appendices, and they use italics.

Underscores, maybe?

2024-05-28 17:30 UTC, Kladki commented
Just to ensure you are aware, I have signed off the pull request now.

2024-05-29 08:07 UTC, richvdh reviewed
Thanks, a couple more things it would be nice to fix while you're here.

2024-05-29 08:07 UTC, richvdh commented on content/rooms/fragments/v8-auth-rules.md
> +the [Handling Redactions](#handling-redactions) section below.
It's only "below" in room v8. It's "above" in room v9. Probably the easiest solution is just to remove "below":

```suggestion
the [Handling Redactions](#handling-redactions) section.
```

2024-05-29 08:07 UTC, richvdh commented on content/rooms/v7.md
> +the [Redactions](#redactions) section below.
likewise in v10 and v11

2024-05-29 08:42 UTC, richvdh approved these changes
Thanks very much!

2024-05-29 08:42 UTC, richvdh commented on content/rooms/v10.md
> +the [Handling redactions](#handling-redactions) section.
It *is* below in v10, but ... :man_shrugging:

2024-05-29 08:42 UTC, merged