Add recommendations for mobile clients
matrix-org/matrix-spec pull request #1915
Opened 2024-08-04 12:10 UTC by agx

When looking into adding UnifiedPush support to a client I was looking around for RFC style "Best Comon Practice" implementation hints but couldn't find any. Maybe it makes sense to add something to the documentation? I couldn't find a more sensible place than the spec if there is one please point me to it?

### Pull Request Checklist

* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#adding-to-the-changelog) (left out as this repo maybe isn't the right location to add this?)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#sign-off)
* [x] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

2024-08-12 08:33 UTC, anoadragon453 requested changes
I think this may go better under https://spec.matrix.org/v1.11/client-server-api/#receiving-notifications.

@matrix-org/rust could I confirm whether this is the best practice for mobile developers to receive (non-)encrypted events?

2024-08-12 08:33 UTC, anoadragon453 commented on content/appendices.md
> +- Use [push notifications][/client-server-api##push-notifications] to get notified about new events
```suggestion
- Use [push notifications][/client-server-api#push-notifications] to get notified about new events
```

2024-08-12 08:33 UTC, anoadragon453 commented on content/appendices.md
> +- Fetch the events indicted in the push notifications via the ``GET /rooms/{roomId}/event/{eventId}`` API call
```suggestion
- Fetch the events included in the push notifications via the ``GET /rooms/{roomId}/event/{eventId}`` API call
```

2024-08-12 08:33 UTC, anoadragon453 commented on content/appendices.md
> +- Fetch the events indicted in the push notifications via the ``GET /rooms/{roomId}/event/{eventId}`` API call
Also, could you linkify `GET /rooms/{roomId}/event/{eventId}`? Likewise with `/sync`?

2024-08-12 08:38 UTC, bnjbvr commented
> @matrix-org/rust could I confirm whether this is the best practice for mobile developers to receive (non-)encrypted events?

Yep, something like this. For what it's worth, instead of using `/context` or `/event` for retrieving the event, we're doing a limited sliding sync, because the two former endpoints don't work for stripped events (coming from invited rooms). And if the event was encrypted, we're indeed trying to run a sliding sync limited to the to-device and encryption extensions; this may change with the new evolution of the sliding sync protocol.

2024-11-26 17:38 UTC, richvdh commented
This feels like it has stalled. @agx: are you able to make the requested changes?

2024-11-28 08:23 UTC, agx commented
> This feels like it has stalled. @agx: are you able to make the requested changes?

Yes, I hope to get to this in the not too distant future.

2025-02-18 15:05 UTC, richvdh commented
I'm going to close this for now. If you'd like to pick this up again, it would be much appreciated: please just ping us and we can reopen.

2025-02-18 15:05 UTC, closed without merging