Update _index.md
matrix-org/matrix-spec pull request #2032
Opened 2024-12-14 20:54 UTC by yoyodragon

### Pull Request Checklist

* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#adding-to-the-changelog)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#sign-off)
* [ ] Pull request is classified as ['other changes'](https://github.com/matrix-org/matrix-spec/blob/master/CONTRIBUTING.rst#other-changes)

2024-12-14 21:51 UTC, richvdh requested changes
I assume this is related to https://github.com/matrix-org/matrix-spec/issues/2030. 

Thank you for the contribution. It's a fair start, but - even though I said "don't try to solve everything at once" -  I think this is the opposite extreme. Just changing the list of modules, without actually changing the name of the section itself, is going to cause confusion. Perhaps you could update your PR so that you're also changing the name of the section itself.

A couple of other points to note:
 * It's helpful to give a bit of description in the PR title about what the PR is trying to achieve. "Update _index.md" doesn't really tell anyone anything.
 * You've ticked "Pull request includes a sign off", but your pull request does not, in fact, include a sign off.

2024-12-15 09:42 UTC, yoyodragon commented
Thank you for the suggestions, I have tried implementing them to the best of my knowledge.
I am new to open source and am not completely aware of the rules and protocols followed, I'm sorry for the inconvenience.Please let me know if I have to make a changelog entry too, I couldn't figure out where to do it.
Thank you.

2024-12-15 17:15 UTC, zecakeh reviewed
> Please let me know if I have to make a changelog entry too, I couldn't figure out where to do it.

Yes, every PR must have a changelog entry. Are the instructions not clear in CONTRIBUTING.rst?

Also this qualifies as "other changes" as far as I can tell.

2024-12-15 17:15 UTC, zecakeh commented on changelogs/legacy/client_server.rst
> +  - Account Data
You should not edit an old changelog entry.

2024-12-15 17:15 UTC, zecakeh commented on data/api/client-server/keys.yaml
> +  title: Matrix Client-Server Account Data API
I don't think this is quite right (but it was already wrong before). Looking at the spec it looks like it should be "Key Management API" for this file.

2024-12-15 17:15 UTC, zecakeh commented on content/client-server-api/_index.md
> +| [Account Data](#client-config)                            | Optional  | Optional | Optional | Optional | Optional |
You also need to apply changes to the URL fragment. `#client-config` should have been changed to `#account-data`, here and maybe in other parts of the spec.

2025-01-02 18:25 UTC, richvdh commented on changelogs/client_server/newsfragments/2032.clarification
> +Rename Client Config to Account Data for issue #2030
```suggestion
Rename "Client Config" section to "Account Data".
```

2025-01-02 18:25 UTC, richvdh commented on changelogs/client_server/newsfragments/2032.clarification
> +Rename Client Config to Account Data for issue #2030
(We don't need the issue number in the changelog.)

2025-01-21 15:12 UTC, closed without merging